### ISSUE TITLE
Re-thresholded bouts are not used

### ISSUE THREAD

**Issue by HsupoLeng** [wohlmp/Ishii_Wohl_DeSouza_Asahina_2019#2]
In function changeJAABAconfidenceValCutoff(.), scores and re-thresholded, and updated bouts are stored in allScores.startNT and allScores.endNT. However, these are never be picked up by smoothBehavBouts(.), because the function always assigns the original, zero-thresholded t0s and t1s to allScores.startth and allScores.endth (see line 16 and 17). In this way, the re-thresholding is in-effective. 

Suggested fix: rename allScores.startth and allScores.endth to allScores.startNT and allScores.endNT, respectively.

**Comment by wohlmp** [comment]
Thanks for catching that! I renamed them at the last minute to reflect other naming conventions and forgot to change those.
